import './globals.css'
import type { Metadata } from 'next'
import { Asap } from 'next/font/google'

import Footer from "./components/footer";
import Header from "./components/header";

const font = Asap({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Challenge - 2.0',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}